travis:
  secure:
    BINSTAR_TOKEN: pdwFcWc7bxYAeK/PjvPtzwKN8u2zTHxk0nKKKMDimXOELt0ERlmvKzr3/190gvcQmu5fBDWqU0sORzkGYmQNsqgKzFwEhbyDv7UlPYXcNaP9pUkBmqzEQ4+e2vFeO9xWPQ4hSKEQqHhxfAfRNfttcIRDxwNxoFBgnkSC7EJ6hq37byqLOAE6utdhHAh40BtYr0Avn7rH53kQaHJ/wsUs6wl7WF8BOuYHjvhCgUqH6c/megc45A8k5WpNP2SFzabxtuXEiLrZhteM0NmI/4kgJ23LGSNQy4TL1Ii7lNA3tWjFQxhSNXvv5VzjoMz5K3GA3/8Q8JdUvcXJWXJM6qU01e7rQL/QWXcxtMtX6nWVyWvnwIrBMkDkHYrBs1OixZDOvDE/p6uZ05IK1KXjzzZmhCwO8gzTdVSh4DzCzUgQc0FBWwGB+jUlLuaBXh4O0tHsao4YY+DZVLkJ7H6seLroBr2b446CQ9/TAbJXX71BKjmey8Nduw3Hc313XKN5WntHSCXyPzJj18V08YJ00jpDf6NwDRBe2S1LlC7TtAcrJR/vjwpnM4bVbTjzBiSBVkBlsdcpZxMgc1k0BXdOuo0HZBGaa9nC51p/iFFDf35YvBXgeB1Nyzp3SXrhgv3QKWNJCBwK7/+AT/0i5omyoislR2s1NgFtuuhAWEScn/2GVlw=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
